# Generated by Django 2.2.19 on 2021-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('release_date', models.DateField()),
                ('author', models.CharField(max_length=100, null=True)),
                ('short_description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
