# Generated by Django 2.2.19 on 2021-03-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInfo',
            new_name='BooksInfo',
        ),
    ]
