# Generated by Django 2.2.19 on 2021-03-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210315_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
