# Generated by Django 2.2.19 on 2021-03-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210317_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksinfo',
            old_name='name',
            new_name='book_title',
        ),
    ]
