# Generated by Django 2.2.19 on 2021-03-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210317_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinfo',
            name='author',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='authentication.Author'),
        ),
    ]
