# Generated by Django 2.2.19 on 2021-03-17 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210317_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
